name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # once daily
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: w2sg-arnav
          template: classic
          base: activity, community, repositories
          config_timezone: Asia/Kolkata

          # ðŸ”½ THIS IS THE MISSING PART
          output_action: commit
          output_path: ./metrics.svg
